# vi: set ft=yaml ts=2:
---

- name: docker repo is absent
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: true
    state: absent

...
