# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_release in in ["xenial"]

- name: gpg key for docker repo is present
  apt_key:
    data: "{{ lookup('file', 'GPG-KEY-docker') }}"
    state: present

- name: docker repo does exist
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: true
    state: present

...
