# vim: set ft=yaml ts=2:
---

- name: remove old ovirt release package
  package:
    name: ovirt-release{{ ovirt.version|replace(".","") }}
    state: absent

- name: remove old yum repos
  block:

    - name: empty old yum repo files
      loop:
        - ovirt-{{ ovirt.version }}.repo
        - ovirt-{{ ovirt.version }}-dependencies.repo
      copy:
        content: '# remove me'
        dest: "/etc/yum.repos.d/{{ item }}"
        backup: true

    - name: remove old yum repo files
      loop:
        - ovirt-{{ ovirt.version }}.repo
        - ovirt-{{ ovirt.version }}-dependencies.repo
      file:
        name: "/etc/yum.repos.d/{{ item }}"
        state: absent

...
