# vim: set ft=yaml ts=2:
---

- debug: var=ovirt.version
  tags:
    - never
    - debug

- debug: msg="{{ ovirt.version|replace('.','') }}"
  tags:
    - never
    - debug

- debug: var=role_path
  tags:
    - never
    - debug

- debug: var=package_repo
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version in ["7"]
      - ovirt.version is defined
      - ovirt.version in ['4.1', '4.2']
      - "(role_path + '/files/RPM-GPG-ovirt-' + ovirt.version|string) is file"

- name: rpm gpg key does exist
  block:
    - name: rpm gpg key does exist
      copy:
        src: RPM-GPG-ovirt-{{ ovirt.version }}
        dest: /etc/pki/rpm-gpg/RPM-GPG-ovirt-{{ ovirt.version }}

    - name: rpm gpg key is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-ovirt-{{ ovirt.version }}
        state: present

- name: EPELs key does exist
  block:
    - name: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} does exist
      copy:
        src: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

- name: CentOS Storage Sig key does exist
  block:
    - name: RPM-GPG-KEY-CentOS-SIG-Storage does exist
      copy:
        src: RPM-GPG-KEY-CentOS-SIG-Storage
        dest: /etc/pki/rpm-gpg/

    - name: RPM-GPG-KEY-CentOS-SIG-Storage E451E5B5 is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Storage
        state: present

- name: RPM-GPG-KEY-CentOS-SIG-OpsTools does exist
  block:
    - name: RPM-GPG-KEY-CentOS-SIG-OpsTools does exist
      copy:
        src: RPM-GPG-KEY-CentOS-SIG-OpsTools
        dest: /etc/pki/rpm-gpg/

    - name: RPM-GPG-KEY-CentOS-SIG-OpsTools 51bc2a13 is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-OpsTools
        state: present

- name: RPM-GPG-KEY-gdeploy does exist
  block:
    - name: RPM-GPG-KEY-gdeploy is present
      copy:
        src: RPM-GPG-KEY-gdeploy
        dest: /etc/pki/rpm-gpg/

    - name: RPM-GPG-KEY-gdeploy 61E8806C is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-gdeploy
        state: present

- name: RPM-GPG-KEY-CentOS-SIG-Virtualization does exist
  block:
    - name: RPM-GPG-KEY-CentOS-SIG-Virtualization is present
      copy:
        src: RPM-GPG-KEY-CentOS-SIG-Virtualization
        dest: /etc/pki/rpm-gpg/

    - name: RPM-GPG-KEY-CentOS-SIG-Virtualization 61E8806C is imported
      ignore_errors: "{{ ansible_check_mode }}"
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization
        state: present

- name: RPM-GPG-KEY-CentOS-SIG-SCLo does exist
  copy:
    src: RPM-GPG-KEY-CentOS-SIG-SCLo
    dest: /etc/pki/rpm-gpg/

- name: RPM-GPG-KEY-CentOS-SIG-SCLo F2EE9D55 is imported
  ignore_errors: "{{ ansible_check_mode }}"
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
    state: present

- name: ovirt-release is present
  package:
    name: ovirt-release{{ ovirt.version|replace('.','') }}
    state: present

- name: ovirt repo is configured
  when: ovirt.version is version('4.1','==')
  template:
    src: ovirt.repo.j2
    dest: /etc/yum.repos.d/ovirt-{{ ovirt.version }}.repo
    backup: true

- debug: var=ovirt.epel_packages['ovirt'+ovirt.version|replace(".","")]|join(",")
  tags:
    - never
    - debug

- debug: var=ovirt.gluster_version['ovirt'+ovirt.version|replace(".","")]
  tags:
    - never
    - debug

- name: ovirt dependency repos are configured
  when: ovirt.version is version('4.1','==')
  template:
    src: ovirt-dependencies.repo.j2
    dest: /etc/yum.repos.d/ovirt-{{ ovirt.version }}-dependencies.repo
    backup: true
